version: "3.9"

services:
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    ports:
    - "27000:27017"
    volumes:
      - mongodb-data-local:/data/mongodb

volumes:
  mongodb-data-local:
    name: mongodb-data-local